### PR TITLE
fix: ui ux bugs

### LINKED ISSUE #203: UI UX Bug fixes
- Spinner
  - After API calls from FE (submit on onboarding, clicking on event from calendar, submit on event modal)
- Event Modal UI upgrades
  - update title to look like an input field
  - update Event Visibility to look like a switch
- After logging in, instead of showing the current date and event, the user is getting redirected to the date when the 1st event was created

### PR DESCRIPTION
**Pull request by iRohitGaur**
### What is the change?

- Spinner
  - After API calls from FE (submit on onboarding, clicking on event from calendar, submit on event modal)
  - no package used - dynamic spinner - shows current date
- Event Modal UI upgrades
  - update title to look like an input field
  - update Event Visibility to look like a switch (created a separate component to set visibility. Existing one will be used to only show the visibility of an event)
- After logging in, instead of showing the current date and event, the user is getting redirected to the date when the 1st event was created
- Added keyboard accessibility to dropdown in onboarding

Provide a small description of what did you change and provide the reference to the issue ticket.

### Is it bug?

- Steps to repro
- Expected
- Actual

### \*Dev Tested?

- [ ] Yes
- [ ] No

#### Platforms

- [ ] Web

#### Browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox

### Before / After Change Screenshots

> For visual or interaction changes. Can be video / screenshot.

Video taken in throttled network - Fast 3G:

https://github.com/Real-Dev-Squad/website-calendar/assets/10892977/97cea280-54f3-4a1d-ad38-99a856db2f61

Screenshot 2023-09-03 at 08 32 10

Screenshot 2023-09-03 at 08 32 34

closes #203

### CODE REVIEW

File: app/routes/onboarding/userDetails.tsx [hunk 1]
```diff
@@ -165,69 +169,72 @@ const UserDetails = () => {
...
-    </Form>
+        <div className=" mx-4 mb-3 basis-1/12">
+          <Button
+            dataTestId="submitButton"
+            label="Submit"
+            size="medium"
+            varient="primary"
+            type={'submit'}
+            style={'my-2'}
+            disabled={![...Object.values(userForm)].every((ele) => ele.length > 0)}
```
Comment (harshith-venkatesh) [inline app/routes/onboarding/userDetails.tsx:232]: Would it be better to have a variable defining what it does and assign condition check variable here?

Comment (iRohitGaur) [reply app/routes/onboarding/userDetails.tsx:232]: @harshith-venkatesh , I did not write this. Its previous code just showing up in green due to change in the structure.

**Review by harshith-venkatesh — APPROVED** [review]
